## MODE SWITCHING -- DON'T MESS WITH (unless you know what you're doing)!
# START mode: dynamic
- url: /js
  static_dir: js
- url: /.*\.(html|css)
  static_dir: html
- url: /img
  static_dir: img
# END mode: dynamic
# START mode: static
#- url: /js
#  static_dir: js
#- url: /.*\.(html|css)
#  static_dir: html-static
# END mode: static
# START mode: production
#- url: /.*\.(html|css)
#  static_dir: html-production
# END mode: production
